[project]
name = "simplefermi"
version = "0.1.0"
description = "Allows for simple uncertainty calculations."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ipython>=8.31.0",
    "matplotlib>=3.10.0",
    "numpy>=2.2.1",
    "pillow>=11.1.0",
    "pint>=0.24.4",
    "pyerf>=1.0.1",
    "termcolor>=2.5.0",
]
