[project]
name = "simplefermi"
version = "0.1.0"
description = "Simple uncertainty calculations."
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "ipython>=8.27.0",
    "matplotlib>=3.9.12",
    "pillow>=11.1.0",
    "pint>=0.24.4",
    "pyerf>=1.0.1",
    "termcolor>=2.5.0",
]
